package service

import (
	"finance-manager-backend/internal/finance-mngr/models"
	"finance-manager-backend/internal/finance-mngr/models/restmodels"
)

type Service interface {

	//Stock service

	//Gets the Balance history of a user's portfolio.
	//uId - The userId to search for
	//d - The number of days to pull history for
	GetUserPortfolioBalanceHistory(uId int, d int) ([]models.PortfolioBalanceHistory, error)

	//User Stock Service

	//Loads the prior User stock for a transaction and updates the Stock being generated by the transaction
	LoadPriorUserStockForTransaction(r restmodels.ModifyStockRequest, usp *models.UserStock, us *models.UserStock) error
}
