package service

import (
	"finance-manager-backend/internal/finance-mngr/models"
	"finance-manager-backend/internal/finance-mngr/models/restmodels"
)

type Service interface {

	//User Stock Service

	//Loads the prior User stock for a transaction and updates the Stock being generated by the transaction
	LoadPriorUserStockForTransaction(r restmodels.ModifyStockRequest, usp *models.UserStock, us *models.UserStock) error
}
