version: '3'

services:

  financemanager:
    build: .
    ports:
      - '8080:8080'
    env_file:
      - .go-env
    depends_on:
      postgres:
        condition: service_healthy
        restart: true

  postgres:
    image: 'postgres:14.5'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: financemanager
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U postgres']
      interval: 5s
      timeout: 50s
      retries: 10
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
